name: Build-Test-Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Use node.js
        uses: actions/setup-node@master
        with:
          node-version: '20'
      - name: Run nmp install
        run: npm install
      - name: Run npm build
        run: npm run build
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Use node.js
        uses: actions/setup-node@master
        with:
          node-version: '20'
      - name: Run nmp install
        run: npm install
      - name: Run npm test
        run: npm test
  
  deploy:
    needs: test

    permissions:
      contents: write
      pages: write
      id-token: write
    
    environment:
      name: Production
      url: ${{ steps.Deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use node.js
        uses: actions/setup-node@master
        with:
          node-version: '20'
      - name: Configure github pages
        uses: actions/configure-pages@master
        with:
          static_site_generator: next
      - name: Run nmp install
        run: npm install
      - name: Run npm build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@master
        with:
          path: './out'
      - name: Deployment
        id: Deployment
        uses: actions/deploy-pages@master