name: Hello-World

on: [push]

jobs:
  Hello-World-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - run: |
          echo "Hello World"
          uname -a
