name: Hello-World

on: [push]

jobs:
  Hello-World-Job:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - run: |
          echo "$(cat hello_world.txt)"
          uname -a
          whoami
          cat /proc/cpuinfo
          free -m
